version: "3.8"
services:
  app:
    image: inedittaappdev
    build:
      context: .
      dockerfile: ./dockerfile.development.yml
    networks:
      - ineditta
    depends_on:
      - database
      - sso
  database:
    image: mysql:oracle
    command: --default-authentication-plugin=mysql_native_password --lc_time_names="pt_BR" --sql_mode="STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION" --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --log-bin-trust-function-creators=1 --sort_buffer_size=1G
    restart: unless-stopped
    networks:
      - ineditta
  sso:
    image: sso
    build:
      context: ./services/auth
      dockerfile: ./Dockerfile
    command:
      - start-dev --spi-x509-cert-lookup-provider nginx --spi-x509-cert-lookup-nginx-enabled true --spi-x509-cert-lookup-nginx-ssl-client-cert ssl-client-cert --spi-x509-cert-lookup-nginx-ssl-cert-chain-prefix USELESS --spi-x509-cert-lookup-nginx-certificate-chain-length 2
    networks:
      - ineditta
    depends_on:
      - ssodb      
  ssodb:
    image: postgres:14.6-alpine
    restart: unless-stopped
    networks:
      - ineditta
  reverse_proxy:
    image: nginx:latest
    networks:
      - ineditta
    depends_on:
      - app
      - sso
  mailhog:
    image: mailhog/mailhog
    networks:
      - ineditta
networks:
  ineditta:
    driver: bridge